/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary:                    '#E85D04',
        'primary-container':        '#c74e00',
        'on-primary':               '#ffffff',
        'on-primary-fixed':         '#360f00',
        'secondary':                '#48C479',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#89f6a4',
        'on-secondary-container':   '#007237',
        'surface':                  '#fcf9f8',
        'surface-bright':           '#fcf9f8',
        'surface-dim':              '#dcd9d9',
        'surface-container':        '#f0eded',
        'surface-container-low':    '#f6f3f2',
        'surface-container-high':   '#eae7e7',
        'surface-container-highest':'#e5e2e1',
        'surface-container-lowest': '#ffffff',
        'on-surface':               '#1c1b1b',
        'on-surface-variant':       '#594137',
        'outline':                  '#8d7165',
        'outline-variant':          '#e1bfb2',
        'background':               '#fcf9f8',
        'on-background':            '#1c1b1b',
        'inverse-surface':          '#313030',
        'inverse-on-surface':       '#f3f0ef',
        'inverse-primary':          '#ffb596',
        'brand-bg':                 '#FFF4EE',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['17px', { lineHeight: '24px', letterSpacing: '0em',     fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':    ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      spacing: {
        'max-width':      '1280px',
        'margin-desktop': '40px',
        'margin-mobile':  '16px',
        'gutter':         '24px',
        'section-gap':    '32px',
        'nav-height':     '64px',
      },
      boxShadow: {
        nav:       '0 2px 12px rgba(0,0,0,0.08)',
        card:      '0 2px 12px rgba(0,0,0,0.08)',
        'card-lg': '0 10px 20px rgba(0,0,0,0.12)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '12px',
        '2xl':   '16px',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
